text = input("Enter the text: ")
old_sub = input("Enter the substring to replace: ")
new_sub = input("Enter the new substring: ")
result = text.replace(old_sub, new_sub)
print("Updated text:", result)
