import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
print("Power:",np.power(a,b))
print("Mod",np.mod(a,b))
print("Remdinder:",np.remainder(a,b))
print("Floor Division:",np.floot_divide(a,b))
print("Absolute:",np.absolute(a))
print("Square Root:",np.sqrt(a))
print("Square:",np.square(a))
print("Cube:",np.cube((a)))
